name: example
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  dartz: ^0.10.1
  dio: ^5.9.0
  freezed_annotation: ^3.1.0
  # path: ^1.9.0

dev_dependencies:
  build_runner: ^2.10.1
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  lints: ^6.0.0
  mg_tools: ^1.0.17
  test: ^1.25.6
