name: swagger_dart_generator
description: A Dart code generator that creates complete Data Layer a Package for Flutter project structure from Swagger/OpenAPI JSON files
version: 1.1.8
homepage: https://github.com/mohamadalghanem474/swagger_dart_generator
repository: https://github.com/mohamadalghanem474/swagger_dart_generator
issue_tracker: https://github.com/mohamadalghanem474/swagger_dart_generator/issues
documentation: https://github.com/mohamadalghanem474/swagger_dart_generator#readme

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.21.0

executables:
  swagger_dart_generator: swagger_dart_generator
